"""empty message

Revision ID: 077fd0f02833
Revises: 5babcd0b02fa
Create Date: 2023-03-16 19:01:46.015452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077fd0f02833'
down_revision = '5babcd0b02fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_departments_name', table_name='departments')
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.create_index('ix_departments_name', 'departments', ['name'], unique=False)
    # ### end Alembic commands ###
