"""empty message

Revision ID: 0cf78cd321de
Revises: 9b79c342384c
Create Date: 2023-03-15 18:49:34.355794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf78cd321de'
down_revision = '9b79c342384c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.add_column('employees', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_positions_name'), 'positions', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_name'), table_name='positions')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_column('employees', 'email')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    # ### end Alembic commands ###
