"""empty message

Revision ID: 5babcd0b02fa
Revises: fb0a148195ff
Create Date: 2023-03-16 07:05:07.892918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5babcd0b02fa'
down_revision = 'fb0a148195ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
