"""empty message

Revision ID: fb0a148195ff
Revises: 0cf78cd321de
Create Date: 2023-03-15 20:08:38.238211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0a148195ff'
down_revision = '0cf78cd321de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
